blank_issues_enabled: true
contact_links:
  - name: 💬 Ask a Question
    url: https://github.com/artificial-intelligence-first/agdd/discussions
    about: For general questions, use Discussions instead of issues
