#!/bin/bash
# Setup Flow Runner for AGDD development
# This script automates the 6-step manual process from README.md

set -e  # Exit on error

FLOW_RUNNER_DIR="${FLOW_RUNNER_DIR:-.flow-runner}"
FLOW_RUNNER_TAG="${FLOW_RUNNER_TAG:-flowrunner-v1.0.0}"

echo "==> Setting up Flow Runner in ${FLOW_RUNNER_DIR}..."

# Step 1: Clone Flow Runner if not already present
if [ -d "${FLOW_RUNNER_DIR}" ]; then
    echo "    Flow Runner directory already exists, skipping clone"
else
    echo "    Cloning Flow Runner repository..."
    git clone https://github.com/artificial-intelligence-first/flow-runner.git "${FLOW_RUNNER_DIR}"
fi

# Step 2: Checkout specific version
echo "    Checking out ${FLOW_RUNNER_TAG}..."
cd "${FLOW_RUNNER_DIR}"
git fetch --tags
git checkout "${FLOW_RUNNER_TAG}"

# Step 3: Sync dependencies
echo "    Syncing dependencies with uv..."
uv sync

# Step 4: Install packages in editable mode
echo "    Installing Flow Runner packages..."
uv pip install -e packages/mcprouter -e packages/flowrunner

cd ..

# Step 5: Generate environment variables file
echo "    Generating flowrunner-env.sh..."
ABSOLUTE_PATH="$(cd "${FLOW_RUNNER_DIR}" && pwd)"
cat > scripts/flowrunner-env.sh <<EOF
#!/bin/bash
# Flow Runner environment variables
# Generated by scripts/setup-flowrunner.sh
# Usage: source scripts/flowrunner-env.sh

export FLOW_RUNNER_DIR="${ABSOLUTE_PATH}"
export FLOW_RUNNER_PYTHONPATH="${ABSOLUTE_PATH}/packages/flowrunner/src:${ABSOLUTE_PATH}/packages/mcprouter/src"

echo "Flow Runner environment configured:"
echo "  FLOW_RUNNER_DIR=${FLOW_RUNNER_DIR}"
echo "  FLOW_RUNNER_PYTHONPATH=${FLOW_RUNNER_PYTHONPATH}"
EOF

chmod +x scripts/flowrunner-env.sh

echo ""
echo "==> Flow Runner setup complete!"
echo ""
echo "To activate Flow Runner environment:"
echo "  source scripts/flowrunner-env.sh"
echo ""
echo "Test commands:"
echo "  uv run agdd flow available"
echo "  uv run agdd flow validate examples/flowrunner/prompt_flow.yaml"
echo ""
