name: "default"
description: "Default routing policy with balanced settings"

routes:
  # Offer orchestration tasks
  - task_type: "offer-orchestration"
    provider: "anthropic"
    model: "claude-3-5-sonnet-20241022"
    use_batch: false
    use_cache: true
    structured_output: true
    moderation: false
    priority: 100
    metadata:
      max_tokens: 4096
      temperature: 0.7

  # Pattern-based routing for offer generation
  - task_type: "offer.generate"
    provider: "anthropic"
    model: "claude-3-5-sonnet-20241022"
    use_batch: false
    use_cache: true
    structured_output: true
    moderation: false
    priority: 90
    metadata:
      max_tokens: 4096
      temperature: 0.7

  # Default fallback for any task
  - task_type: "*"
    provider: "anthropic"
    model: "claude-3-5-sonnet-20241022"
    use_batch: false
    use_cache: false
    structured_output: false
    moderation: false
    priority: 0
    metadata:
      max_tokens: 2048
      temperature: 0.5
